language: go

sudo: false

go:
  - '1.14'
  - '1.15'
  - tip

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.34.1

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - make lint
  - ./.travis.gofmt.sh
  - ./.travis.test.sh